config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  get 'trainings/certificate'
  get 'trainings/new'
  get 'trainings/download'

end

app/models/training.rb
class Training < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  require 'erb'

  def index
    @agarwal = {abc: "sandhya", cde: "shree"}
  end

  def get_binding
    binding
  end

  def show

  end

  def certificate
    controller =TrainingsController.new
    controller.index
    erb_file = 'app/views/trainings/certificate.html.erb'
    file_name = File.basename(erb_file, '.erb')
    html_file = "app/views/trainings/nikhil.html"
    @agarwal = controller.index
    erb_str = File.read(erb_file)
    renderer = ERB.new(erb_str)
    result = renderer.result(controller.get_binding)
    File.open(html_file, 'w') do |f|
      f.write(result)
    end
  end


  def download
    output = render_to_string "nikhil.html"
    kit = PDFKit.new(output)
    pdf = kit.to_file 'public/data/my.pdf'
    send_file(
    "#{Rails.root}/public/data/my.pdf",
    filename: "certificate.pdf",
    type: "application/pdf"
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CertificatePdf</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trainings/certificate.html.erb
hi this is certificate page <%= @agarwal[:abc] %>
<%= @agarwal[:cde] %>

app/views/trainings/new.html.erb
heloooooooooooooooo
download from here
<p><%= link_to 'View Certificate', trainings_certificate_url %></p>
<p><%= link_to 'Download Certificate', trainings_download_url %></p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>